/*
 * Automatically generated by jrpcgen 1.1.0 on 15-1-30 上午8:57
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */

import org.acplt.oncrpc.*;
import java.io.IOException;

import java.net.InetAddress;

import org.acplt.oncrpc.server.*;

/**
 */
public abstract class MyRPCDemoServerStub extends OncRpcServerStub implements OncRpcDispatchable {

    public MyRPCDemoServerStub()
           throws OncRpcException, IOException {
        this(0);
    }

    public MyRPCDemoServerStub(int port)
           throws OncRpcException, IOException {
        this(null, port);
    }

    public MyRPCDemoServerStub(InetAddress bindAddr, int port)
           throws OncRpcException, IOException {
        info = new OncRpcServerTransportRegistrationInfo [] {
            new OncRpcServerTransportRegistrationInfo(MyRPCDemo.RPC_ONC_DEMO, 1),
        };
        transports = new OncRpcServerTransport [] {
            new OncRpcUdpServerTransport(this, bindAddr, port, info, 32768)
            ,
            new OncRpcTcpServerTransport(this, bindAddr, port, info, 32768)
        };
    }

    public void dispatchOncRpcCall(OncRpcCallInformation call, int program, int version, int procedure)
           throws OncRpcException, IOException {
        if ( version == 1 ) {
            switch ( procedure ) {
            case 1: {
                XdrString args$ = new XdrString();
                call.retrieveCall(args$);
                XdrString result$ = new XdrString(SayHello_1(args$.stringValue()));
                call.reply(result$);
                break;
            }
            case 0: {
                call.retrieveCall(XdrVoid.XDR_VOID);
                call.reply(XdrVoid.XDR_VOID);
                break;
            }
            default:
                call.failProcedureUnavailable();
            }
        } else {
            call.failProgramUnavailable();
        }
    }

    public abstract String SayHello_1(String arg1);

}
// End of MyRPCDemoServerStub.java
