/*
 * Automatically generated by jrpcgen 1.1.0 on 15-1-30 上午8:57
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */

import org.acplt.oncrpc.*;
import java.io.IOException;

import java.net.InetAddress;

/**
 * The class <code>MyRPCDemoClient</code> implements the client stub proxy
 * for the RPC_ONC_DEMO remote program. It provides method stubs
 * which, when called, in turn call the appropriate remote method (procedure).
 */
public class MyRPCDemoClient extends OncRpcClientStub {

    /**
     * Constructs a <code>MyRPCDemoClient</code> client stub proxy dummy.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public MyRPCDemoClient() throws OncRpcException, IOException {
        super(null);
    }

    /**
     * Constructs a <code>MyRPCDemoClient</code> client stub proxy object
     * from which the RPC_ONC_DEMO remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public MyRPCDemoClient(InetAddress host, int protocol)
           throws OncRpcException, IOException {
        super(host, MyRPCDemo.RPC_ONC_DEMO, 1, 0, protocol);
    }

    /**
     * Constructs a <code>MyRPCDemoClient</code> client stub proxy object
     * from which the RPC_ONC_DEMO remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param port Port number at host where the remote program can be reached.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public MyRPCDemoClient(InetAddress host, int port, int protocol)
           throws OncRpcException, IOException {
        super(host, MyRPCDemo.RPC_ONC_DEMO, 1, port, protocol);
    }

    /**
     * Constructs a <code>MyRPCDemoClient</code> client stub proxy object
     * from which the RPC_ONC_DEMO remote program can be accessed.
     * @param client ONC/RPC client connection object implementing a particular
     *   protocol.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public MyRPCDemoClient(OncRpcClient client)
           throws OncRpcException, IOException {
        super(client);
    }

    /**
     * Constructs a <code>MyRPCDemoClient</code> client stub proxy object
     * from which the RPC_ONC_DEMO remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param program Remote program number.
     * @param version Remote program version number.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public MyRPCDemoClient(InetAddress host, int program, int version, int protocol)
           throws OncRpcException, IOException {
        super(host, program, version, 0, protocol);
    }

    /**
     * Constructs a <code>MyRPCDemoClient</code> client stub proxy object
     * from which the RPC_ONC_DEMO remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param program Remote program number.
     * @param version Remote program version number.
     * @param port Port number at host where the remote program can be reached.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public MyRPCDemoClient(InetAddress host, int program, int version, int port, int protocol)
           throws OncRpcException, IOException {
        super(host, program, version, port, protocol);
    }

    /**
     * Call remote procedure SayHello_1.
     * @param arg1 parameter (of type String) to the remote procedure call.
     * @return Result from remote procedure call (of type String).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public String SayHello_1(String arg1)
           throws OncRpcException, IOException {
        XdrString args$ = new XdrString(arg1);
        XdrString result$ = new XdrString();
        client.call(MyRPCDemo.SayHello_1, MyRPCDemo.DEMO_FIRST_VERSION, args$, result$);
        return result$.stringValue();
    }

}
// End of MyRPCDemoClient.java
