/*
 * Automatically generated by jrpcgen 1.1.0 on 15-1-30 上午8:57
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */

/**
 * A collection of constants used by the "MyRPCDemo" ONC/RPC program.
 */
public interface MyRPCDemo {
    public static final int RPC_ONC_DEMO = 0x20000001;
    public static final int SayHello_1 = 1;
    public static final int DEMO_FIRST_VERSION = 1;
}
// End of MyRPCDemo.java
